# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d63d02f6a271ad2d70a00c49a9f28bb237e53fb8cdb2440b3015291c11a1865537115cc6ce567c262c9bcb7036868c5923d99051c7ea4d83be437b20990560c

test:
  secret_key_base: 379463f4482e94d26bfd01307ec6704c036368cb996d6eeeca2bac198fddb2ff1ae1c846f1d38567a962e273b33250bc947a5c367f4b87dfb92bd3589ac346a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
